import './main.css';
import Header from "./_components/Header";
import Provider from './_components/ThemeProvider';

export const metadata = {
  title: {
    template: "%s | Weather app",
    default: 'Weather App'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="bg-background text-text dark:bg-darkMode-background dark:text-darkMode-text mb-6" >
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
